version: "2"
services:
  web:
    image: nodejsapp:latest
    ports:
    - "8080:8080"
    depends_on:
    - mongocfglatest
    - mongocfg2
    - mongocfg3
    - mongoslatest
    - mongos2
  mongocfglatest:
    container_name: mongocfglatest
    image: mongo
    command: mongod --configsvr --replSet mongorslatestconf --dbpath /data/db --port 270latest7
    environment:
      TERM: xterm
    expose:
      - "270latest7"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/configlatest:/data/db
  mongocfg2:
    container_name: mongocfg2
    image: mongo
    command: mongod --configsvr --replSet mongorslatestconf --dbpath /data/db --port 270latest7
    environment:
      TERM: xterm
    expose:
      - "270latest7"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/config2:/data/db
  mongocfg3:
    container_name: mongocfg3
    image: mongo
    command: mongod --configsvr --replSet mongorslatestconf --dbpath /data/db --port 270latest7
    environment:
      TERM: xterm
    expose:
      - "270latest7"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_cluster/config3:/data/db
  mongoslatest:
    container_name: mongoslatest
    image: mongo
    depends_on:
      - mongocfglatest
      - mongocfg2
    command: mongos --configdb mongorslatestconf/mongocfglatest:270latest7,mongocfg2:270latest7,mongocfg3:270latest7 --port 270latest7
    ports:
      - 270latest9:270latest7
    expose:
      - "270latest7"
    volumes:
      - /etc/localtime:/etc/localtime:ro
  mongos2:
    container_name: mongos2
    image: mongo
    depends_on:
      - mongocfglatest
      - mongocfg2
    command: mongos --configdb mongorslatestconf/mongocfglatest:270latest7,mongocfg2:270latest7,mongocfg3:270latest7 --port 270latest7
    ports:
      - 27020:270latest7
    expose:
      - "270latest7"
    volumes:
      - /etc/localtime:/etc/localtime:ro
